Jack/cf 1731 ability to check token expiration and prompt user for re
common-fate/glide-cli pull request #42
Opened 2023-08-01 23:19 UTC by meyerjrr

Checks expiry date of token and if `--lazy` flag is passed, will not initiate login flow if expiring is not within 5 minutes

2023-08-03 00:14 UTC, Eddie023 approved these changes

2023-08-03 00:14 UTC, Eddie023 commented on cmd/command/login.go
> +			clio.Infow("Auth token still valid, skipping login flow.")
Maybe debug log instead of info log

2023-08-03 10:58 UTC, chrnorm commented on cmd/command/login.go
> +		&cli.BoolFlag{Name: "lazy", Usage: "the lazy flag lets granted decide whether a new login flow should be initiated based on the token expiry", Aliases: []string{"l"}},
I don't think this will be used enough outside of scripts to warrant a short alias

```suggestion
		&cli.BoolFlag{Name: "lazy", Usage: "the lazy flag lets granted decide whether a new login flow should be initiated based on the token expiry"},
```

2023-08-03 11:07 UTC, chrnorm requested changes

2023-08-03 11:07 UTC, chrnorm commented on cmd/command/login.go
> +		if timeDifference > targetTime {
this is more complex than it needs to be and is difficult to read - in Go there are simpler ways to compare times. As a reviewer it's difficult to tell if the logic is correct here.

I would suggest something like the following:

```
expiry := token.Expiry

// if the token expires up to 5 minutes in the future,
// refresh it now.
timeToRefresh := time.Now().Add(5*time.Minute)

if expiry.Before(timeToRefresh) {
	// do logic to refresh the token
}
```

Could you then please extract this logic out to a small function and then add a unit test to sanity check it? The function should be something like

```
func shouldRefreshToken(token oauth2.Token, now time.Time) bool {

}
```

and then you can add a couple of tests to verify that the token is refreshed based on the current `now` value.

2023-08-03 11:10 UTC, chrnorm submitted a review, later dismissed

2023-08-03 11:10 UTC, chrnorm commented on pkg/client/client.go
>  		e.Messages = append(e.Messages, clierr.Infof("To log in to Common Fate, run: '%s'", rd.LoginHint))
I think there is a logic error here - returning early will discard the `res` value as you have set it to `nil` in the code you've added.

```suggestion
		if cfContext.DashboardURL != "" {
			e.Messages = append(e.Messages, clierr.Infof("To log in to Common Fate, run: '%s %s'", rd.LoginHint, cfContext.DashboardURL))
		} else {
		        e.Messages = append(e.Messages, clierr.Infof("To log in to Common Fate, run: '%s'", rd.LoginHint))
		 }
```

2023-08-04 00:33 UTC, Eddie023 approved these changes

2023-08-04 00:43 UTC, merged